const express = require('express')
const router = require('./routes/index')
const app = express()
const path = require('path')
app.use(router)
app.use(express.static(path.resolve(__dirname, './public')))
app.listen(9000, () => {})
